sudo: required
language: java

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo apt-get install python3
  - cd rabix-integration-testing
  - git clone https://github.com/rabix/common-workflow-language.git
  - pwd
  - ls -ltra	
  - cd ..

install:
  - pip install -e git+https://github.com/common-workflow-language/cwltest.git@master#egg=cwltest

script:
  - pwd
  - ls -ltra
  - mvn clean install package -P draft-2
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -e -X

cache:
  directories:
  - $HOME/.m2

notifications:
  email:
    recipients:
      - marko.vukobrat@sbgenomics.com
      - janko.simonovic@sbgenomics.com
      - sinisa.ivkovic@sbgenomics.com
    on_success: always
    on_failure: always 

