sudo: required
language: java

services:
  - docker

script:
  - mvn clean install package
  - mvn org.codehaus.mojo:exec-maven-plugin:1.5.0:java -pl rabix-integration-testing -Dexec.mainClass="org.rabix.tests.TestRunner" -e -X
 
