bunny_engine_url: http://localhost:8081
cache_directory: /Users/janko/Desktop/Archive/varscan
engine_heartbeat_interval: 20
mocks_file: /home/milos/tools/bunny_mock_backend/config/mocks.json

rabbitmq_host: localhost
rabbitmq_auth: bunny:bunny
rabbitmq_vhost: bunny
rabbitmq_engine_exchange: engine_exchange
rabbitmq_receive_routing_key: receive_routing_key
rabbitmq_heartbeat_routing_key: heartbeat_routing_key

